### ISSUE TITLE
v4 roadmap

### ISSUE THREAD

**Issue by artalar** [artalar/reatom#841]
The upcoming version "4" will feature several changes, but most will be straightforward to migrate. Here is the list of main changes.

- [ ] Publish only an ESM bundle
  > It's still being discussed.
- [x] Store all code in a single package (`@reatom/framework`), except for adapters.
  > This will simplify code organization and versioning for both library authors and consumer developers.
- [x] Remove "FRP" operators from `@reatom/lens`.
  > We aim to reduce the number of variants for solving the same task; most operators will be replaced with guidelines that follow best practices.
  - [x] add `filter` operator as an alternative to existing `select`, which accepts an atom and the mapper function `(next: State, prev?: State) => T`.
- [x] #844
  > This is necessary for feature migration to implicit context ("AsyncContext"). For explicit usage of "spy" or "get" semantics, we will export additional methods.
- [x] #845
- [x] Deprecate the `pipe` operator in favor of the more capable `mix` operator.
  > We have received feedback that "pipe" is strongly associated with RxJS, which is not accurate, but marketing considerations take precedence here.
- [x] Replace `reatomAsync` with a regular action that includes an async function, and replace `reatomResource` with a standard atom that includes an async function.
  > This will enable applying all async operators for all actions and atoms! Also, we plan to allow asynchronous "spy" of dependencies!
- [x] Adopt a "suspense" strategy for error handling. This will open up a whole new vector of a simple and robust coding style.
- [x] Add autobatching with release change on a next tick.
- [ ] Change `withRetry` api
  > The `onReject` cb should return not the amount of ms to retry, but the promise which successful resolve should mean the necessity of retry (and an error  (abort error) should prevent retries).
- [x] Run the third argument of `take` immediately for an atoms to return the state without waiting, if it is already pass.

Minor fixes:

- [ ] https://github.com/artalar/reatom/pull/518

**Comment by Guria** [comment]
@artalar I think it is time to update/close this a bit confusing ticket
